### ISSUE TITLE
112.06.00 build failure with OCaml 4.02.0

### ISSUE THREAD

**Issue by cjf-666** [janestreet/custom_printf#3]
I noticed `Scan_next_char` was recently introduced in 112.06.00, didn't show up in 112.01.00

> File "syntax/pa_custom_printf.ml", line 165, characters 8-22:
> Error: This variant pattern is expected to have type
>         (a, b, c, d, e, f) CamlinternalFormatBasics.fmt
>       The constructor Scan_next_char does not belong to type CamlinternalFormatBasics.fmt
> Command exited with code 2.

Then I looked it up in the [mannul](http://caml.inria.fr/pub/docs/manual-ocaml/libref/CamlinternalFormatBasics.html) and found that it wasn't there.

Not sure if I misunderstood anything, hopefully helpful. Thanks.

**Comment by ghost** [comment]
I didn't check but it might have been added in 4.02.1.
